config/routes.rb
LOLcat::Application.routes.draw do
  resources :abouts

  resources :meals

  devise_for :users

  resources :sponsors

  resources :chefs

  resources :teams

  get "welcome/index"

   root :to => 'welcome#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :chefs
  	
  attr_accessible :chef, :date, :description, :location, :name, :pickup_time

  validates :date, presence: true

  validates :name, presence: true

  validates :chef, presence: true

  validates :pickup_time, presence: true

  validates :description, presence: true

  validates :location, presence: true

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chef %><br />
    <%= f.collection_select :chef, Chef.all, :name, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :pickup_time %><br />
    <%= f.time_select :pickup_time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="actions">
    <%= f.submit "Create New Meal", :class => "round button" %>
  </div>

<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<center><h1>Meals of the Month</h1></center>



<center><a class="btn btn-large btn-success" href="/meals/new">Create A New Meal</a></center>
<br></br>
<div id="calendar">
 <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
 </h2>
  <%= calendar_for @meals, :year => @date.year, :month => @date.month do |calendar|  %>
  <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
  <%= calendar.day(:day_method => :date) do |date, meals| %>
    <%= date.day %>
    <ul>
        <% for meal in meals %>
          <li><%= link_to h(meal.name), meal %></li>
        <% end %>
    </ul>
    <% end %>
  <% end %>
</div>
<br></br>

<center><h1>List of all Meals</h1></center>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Chef</th>
    <th>Date</th>
    <th>Pickup time</th>
    <th>Location</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.name %></td>
    <td><%= meal.chef %></td>
    <td><%= meal.date %></td>
    <td><%= meal.pickup_time %></td>
    <td><%= meal.location %></td>
    <td><%= meal.description %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meal.name %>
</p>

<p>
  <b>Chef:</b>
  <%= @meal.chef %>
</p>

<p>
  <b>Date:</b>
  <%= @meal.date %>
</p>

<p>
  <b>Pickup time:</b>
  <%= @meal.pickup_time %>
</p>

<p>
  <b>Location:</b>
  <%= @meal.location %>
</p>

<p>
  <b>Description:</b>
  <%= @meal.description %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>