config/routes.rb
LOLcat::Application.routes.draw do
  resources :abouts

  resources :meals

  devise_for :users

  resources :sponsors

  resources :chefs

  resources :teams

  get "welcome/index"

   root :to => 'welcome#index'

end

app/models/about.rb
class About < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.json
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render json: @about, status: :created, location: @about }
      else
        format.html { render action: "new" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.json
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to abouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_for(@about) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render 'form' %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>About Foodies Connect</h1>

<div class="container">

      <h2>How Does it Work?</h2>
      <br></br>
      <p>If you are a Foodie this is perfect for you! Whether you like to cook or like to eat you'll find many ways to satisfy your appetite<br> If you like to cook, sign up to be a chef on the home page. If you like to eat check out the calendar and create a meal with a chef!</p>

    </div> <!-- /container -->

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>